apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinebookdep
  namespace: firstns
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  minReadySeconds: 30
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
      - name: onlinecont
        image: nanddockerhub/onlined:ImageTag
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: onlinesvc
  namespace: firstns
spec:
  type: NodePort
  selector:
    app: book
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000

  
